import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'punttj' at '2/8/17 4:40 PM' with Gradle 2.14.1
 *
 * @author punttj, @date 2/8/17 4:40 PM
 */
public class LibraryTest {
    
	@Test
	public void TrueTest(){
		assertEquals(true, true);
	}
}
